image:https://github.com/toedter/spring-hateoas-jsonapi-examples/workflows/Build/badge.svg["build", link="https://github.com/toedter/spring-hateoas-jsonapi/actions"]
image:https://img.shields.io/badge/License-Apache%202.0-blue.svg["Apache 2.0", link="https://opensource.org/licenses/Apache-2.0"]

= JSON:API for Spring HATEOAS Examples

This repository contains example projects to interact with https://github.com/toedter/spring-hateoas-jsonapi[JSON:API for Spring HATEOAS].

== Examples

=== example-model
In this library project the data model used by all examples is defined.

=== example-basic
Basic usage of the representation models provided by Spring HATEOAS.
No JSON:API specific features are used, but the resulting JSON is rendered as JSON:API.

=== example-advances
Advanced usage of JSON:API specific features like relationships, included resources and sparse fieldsets.

== Running the Examples

* Make sure Java 8 or later JDK is installed
* Clone this Git repository and cd into `spring-hateoas-jsonapi`
* cd to the example directory
* Invoke `../gradlew bootrun` (`..\gradlew` on Windows)
* Open link:++http://localhost:8080/api/movies

== License

Apache 2.0, see https://opensource.org/licenses/Apache-2.0
