:doctype: book
image:https://github.com/toedter/spring-hateoas-jsonapi-examples/workflows/Build/badge.svg["build", link="https://github.com/toedter/spring-hateoas-jsonapi/actions"]
image:https://img.shields.io/badge/License-Apache%202.0-blue.svg["Apache 2.0", link="https://opensource.org/licenses/Apache-2.0"]

= JSON:API for Spring HATEOAS Examples

This repository contains example projects to interact with https://github.com/toedter/spring-hateoas-jsonapi[JSON:API for Spring HATEOAS].

== Examples

=== example-model
In this library project the data model used by all examples is defined.
Movie and Director are the JPA Entities, also Spring Data repositories are defined
and filled with 250 sample movies.

=== example-basic
Basic usage of the representation models provided by Spring HATEOAS.
No JSON:API specific features are used, but the resulting JSON is rendered as JSON:API.

=== example-advanced
Advanced usage of JSON:API specific features like relationships, included resources and sparse fieldsets.

=== example-restdocs-openapi
This example is currently not working because https://github.com/ePages-de/restdocs-api-spec[restdocs-api-spec]
is not ported to Spring REST Docs 3.0.0 yet.

This adds test to the example-advanced that produce an OpenAPI v3 specification.
You can create the spec running `../gradlew openapi3`. You find the generated spec at
`build/api-spec/openapi3.yaml`

== Running the Examples

* Make sure Java 8 or later JDK is installed
* Clone this Git repository and cd into `spring-hateoas-jsonapi`
* cd to the one of the example directories
* Invoke `../gradlew bootrun` (`..\gradlew` on Windows)
* Open http://localhost:8080/api/movies

== License

Apache 2.0, see https://opensource.org/licenses/Apache-2.0
