### Create a new movie
POST http://localhost:8080/api/movies
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "movies",
    "attributes": {
      "title": "Inception",
      "year": 2010,
      "imdbId": "tt1375666",
      "rating": 8.8,
      "rank": 13
    }
  }
}
